### ISSUE TITLE
Source Maps support

### ISSUE THREAD

**Issue by joaocunha** [ggkovacs/node-px2rem#1]
Great stuff, buddy. I love writing everything in `px`. How about Source Maps support? I'm using the gulp version and it breaks it.

I tried `.pipe(px2rem({replace: false}, {map:true}))` and it inlines the sourcemap in a strange way. Using `    .pipe(px2rem({replace: false}, {map:{inline:false}}))` to get an external map seems to have no effect whatsoever.

**Comment by ggkovacs** [comment]
Thanks. If you want to use sourcemaps you can use this: [`gulp-sourcemaps`](https://www.npmjs.com/package/gulp-sourcemaps)

**Comment by joaocunha** [comment]
@ggkovacs I tried it. Would you mind showing me a snippet?

**Comment by ggkovacs** [comment]
gulpfile.js
```js
'use strict';

var gulp = require('gulp');
var px2rem = require('gulp-px2rem');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('css', function() {
    gulp.src('main.css')
        .pipe(sourcemaps.init())
        .pipe(px2rem())
        .pipe(sourcemaps.write('../maps'))
        .pipe(gulp.dest('build'));
});
```

**Comment by andrewmartin** [comment]
Does this work? It seems to not work for me at all. I have a very similar setup to what @ggkovacs had.

**Comment by mqliutie** [comment]
Yeah, This config will delete `sourceMappingURL`  

`sourcemap `will does not work!
